### ISSUE TITLE
Does ical2org support repeating tasks

### ISSUE THREAD

**Issue by jagguli** [ical2org-py/ical2org.py#15]
Why does it generate individual tasks instead of using http://orgmode.org/manual/Repeated-tasks.html

**Comment by asoroa** [comment]
I was just unaware of these repeated tasks when developing the tool. It seems like a very good idea, but it would require a) see if the actual functionality is preserved when using the repeated tasks and b) re-implement the whole script ;-)

If a) is fulfilled I may consider doing b)

**Comment by io12** [comment]
> I was just unaware of these repeated tasks when developing the tool. It seems like a very good idea, but it would require a) see > if the actual functionality is preserved when using the repeated tasks and b) re-implement the whole script ;-)
>
> If a) is fulfilled I may consider doing b)

I think a) is fulfilled.

**Comment by spookylukey** [comment]
The ical format supports a lot of ways of doing repeated items - see https://github.com/niccokunzmann/python-recurring-ical-events for more information.

Because of this, it's very unlikely that the Emacs functionality will provide equal and compatible functionality. Even for the subset where we could match it, we'd have to be able to reliable work that out, which would be pretty much another re-implementation of the library above.

So, I think it best we keep to the current method.
